# Generated by Django 5.2.5 on 2025-10-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_original', models.TextField()),
                ('remetente', models.CharField(max_length=20)),
                ('risco_ia', models.CharField(max_length=20)),
                ('analise_ia', models.TextField()),
                ('feedback_usuario_correto', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
