# Generated by Django 5.2.5 on 2025-11-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='treinamento_concluido',
            field=models.BooleanField(default=False),
        ),
    ]
