# Generated by Django 5.1.4 on 2026-03-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_feedback_treinamento_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='remetente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='risco_ia',
            field=models.CharField(max_length=50),
        ),
    ]
